/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Interface;

import Model.Product;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author swapn
 */
public class BankRecordsJPanel extends javax.swing.JPanel {
    
    Product product;
    private boolean errorcode_AccountType;
    private boolean errorcode_AccountOwner;
    private boolean errorcode_AccountProfile;
    private boolean errorcode_Name;
    private boolean errorcode_AccountNumber;
    private boolean errorcode_RoutingNumber;

    /**
     * Creates new form BankRecordsJPanel
     */
    public BankRecordsJPanel(Product product) {
        initComponents();
        this.product = product ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAccountType = new javax.swing.ButtonGroup();
        buttonGroupAccountOwner = new javax.swing.ButtonGroup();
        buttonGroupProfile = new javax.swing.ButtonGroup();
        lbl_BankRecordsTitle = new javax.swing.JLabel();
        lbl_AccountType = new javax.swing.JLabel();
        rb_Checking = new javax.swing.JRadioButton();
        rb_Savings = new javax.swing.JRadioButton();
        lbl_AccountOwner = new javax.swing.JLabel();
        rb_Owner = new javax.swing.JRadioButton();
        rb_NotOwner = new javax.swing.JRadioButton();
        lbl_Profile = new javax.swing.JLabel();
        rb_Personal = new javax.swing.JRadioButton();
        rb_Business = new javax.swing.JRadioButton();
        lbl_Name = new javax.swing.JLabel();
        lbl_RoutingNo = new javax.swing.JLabel();
        lbl_AccountNo = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        txt_RoutingNo = new javax.swing.JTextField();
        txt_AccountNo = new javax.swing.JTextField();
        lbl_Save = new javax.swing.JButton();
        lbl_Warning = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_BankRecordsTitle.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lbl_BankRecordsTitle.setText("BANK RECORDS");
        add(lbl_BankRecordsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 11, -1, -1));

        lbl_AccountType.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_AccountType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_AccountType.setText("* Account Type : ");
        lbl_AccountType.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbl_AccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 56, -1, -1));

        buttonGroupAccountType.add(rb_Checking);
        rb_Checking.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        rb_Checking.setText("Checking");
        add(rb_Checking, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 52, -1, -1));

        buttonGroupAccountType.add(rb_Savings);
        rb_Savings.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        rb_Savings.setText("Savings");
        add(rb_Savings, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 52, -1, -1));

        lbl_AccountOwner.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_AccountOwner.setText("* Account Owner : ");
        add(lbl_AccountOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 97, -1, -1));

        buttonGroupAccountOwner.add(rb_Owner);
        rb_Owner.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        rb_Owner.setText("I'm the owner");
        add(rb_Owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 93, -1, -1));

        buttonGroupAccountOwner.add(rb_NotOwner);
        rb_NotOwner.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        rb_NotOwner.setText("I'm not the owner");
        add(rb_NotOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 93, -1, -1));

        lbl_Profile.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_Profile.setText("* Profile :");
        add(lbl_Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 138, -1, -1));

        buttonGroupProfile.add(rb_Personal);
        rb_Personal.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        rb_Personal.setText("Personal");
        add(rb_Personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 134, -1, -1));

        buttonGroupProfile.add(rb_Business);
        rb_Business.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        rb_Business.setText("Business");
        add(rb_Business, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 134, -1, -1));

        lbl_Name.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_Name.setText("* Name : ");
        add(lbl_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 178, -1, -1));

        lbl_RoutingNo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_RoutingNo.setText("* Routing Number :");
        add(lbl_RoutingNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 217, -1, -1));

        lbl_AccountNo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_AccountNo.setText("* Account Number : ");
        add(lbl_AccountNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 256, -1, -1));

        txt_Name.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txt_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 175, 150, -1));

        txt_RoutingNo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_RoutingNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txt_RoutingNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 214, 150, -1));

        txt_AccountNo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_AccountNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txt_AccountNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 253, 150, -1));

        lbl_Save.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        lbl_Save.setText("Save");
        lbl_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_SaveActionPerformed(evt);
            }
        });
        add(lbl_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 292, -1, -1));

        lbl_Warning.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        lbl_Warning.setForeground(new java.awt.Color(255, 0, 0));
        lbl_Warning.setText("All fields marked with * are Mandatory.");
        add(lbl_Warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Interface/view.gif"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Radiobutton(java.awt.event.ActionEvent evt)
    {
        if (rb_Checking.isSelected())
            rb_Savings.setVisible(true);
    }
    
    private void lbl_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_SaveActionPerformed
        // TODO add your handling code here:
        
        
        if (rb_Checking.isSelected() == true)
            product.setAccount_Type("Checking");
        else if (rb_Savings.isSelected() == true)
            product.setAccount_Type("Savings");
        else
            errorcode_AccountType = true;
        
        if (rb_Owner.isSelected() == true)
            product.setAccount_Owner("You're the owner");
        else if (rb_NotOwner.isSelected() == true)
            product.setAccount_Owner("You're not the owner");
        else
            errorcode_AccountType = true;
        
        if (rb_Personal.isSelected() == true)
            product.setAccount_Profile("Personal");
        else if (rb_Business.isSelected() == true)
            product.setAccount_Profile("Business");
        else
            errorcode_AccountProfile = true;
        
        errorcode_Name = Pattern.matches("^[0-9]*$", txt_Name.getText());
        errorcode_RoutingNumber = Pattern.matches("^[0-9]*$", txt_RoutingNo.getText());
        errorcode_AccountNumber = Pattern.matches("^[0-9]*$", txt_AccountNo.getText());
        
        
        if (txt_Name.getText().isBlank() || txt_RoutingNo.getText().isBlank() || txt_AccountNo.getText().isBlank() || errorcode_AccountType == true || errorcode_AccountType == true || errorcode_AccountProfile == true)
            JOptionPane.showMessageDialog(this, "Mandatory fields cannot be blank.");
        else if (errorcode_Name == true)
            JOptionPane.showMessageDialog(this, "Name cannot contain Numbers.");
        else if (errorcode_RoutingNumber == false)
            JOptionPane.showMessageDialog(this, "Routing Number should be Numeric.");
        else if (errorcode_AccountNumber == false)
            JOptionPane.showMessageDialog(this, "Account Number should be Numeric.");
        else
        {   product.setAccount_Holder_Name(txt_Name.getText());
            product.setRouting_Number(txt_RoutingNo.getText());
            product.setAccount_Number(txt_AccountNo.getText());
            JOptionPane.showMessageDialog(this, "Bank Details has been Saved");
        }
       
    }//GEN-LAST:event_lbl_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAccountOwner;
    private javax.swing.ButtonGroup buttonGroupAccountType;
    private javax.swing.ButtonGroup buttonGroupProfile;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_AccountNo;
    private javax.swing.JLabel lbl_AccountOwner;
    private javax.swing.JLabel lbl_AccountType;
    private javax.swing.JLabel lbl_BankRecordsTitle;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Profile;
    private javax.swing.JLabel lbl_RoutingNo;
    private javax.swing.JButton lbl_Save;
    private javax.swing.JLabel lbl_Warning;
    private javax.swing.JRadioButton rb_Business;
    private javax.swing.JRadioButton rb_Checking;
    private javax.swing.JRadioButton rb_NotOwner;
    private javax.swing.JRadioButton rb_Owner;
    private javax.swing.JRadioButton rb_Personal;
    private javax.swing.JRadioButton rb_Savings;
    private javax.swing.JTextField txt_AccountNo;
    private javax.swing.JTextField txt_Name;
    private javax.swing.JTextField txt_RoutingNo;
    // End of variables declaration//GEN-END:variables
}
