/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Interface;

import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author swapn
 */
public class HealthRecordJPanel extends javax.swing.JPanel {
    
    Product product;
    private String Other_Medical_History;

    /**
     * Creates new form HealthRecordJPanel
     */
    public HealthRecordJPanel(Product product) {
        initComponents();
        this.product = product ;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_HealthRecord_Title = new javax.swing.JLabel();
        lbl_MedicalRecordNo = new javax.swing.JLabel();
        lbl_HealthPlanNo = new javax.swing.JLabel();
        lbl_PreviousMedicalHist = new javax.swing.JLabel();
        lbl_message1 = new javax.swing.JLabel();
        chkbox_diabetes = new javax.swing.JCheckBox();
        chkbox_Hypertension = new javax.swing.JCheckBox();
        chkbox_Allergies = new javax.swing.JCheckBox();
        chkbox_OtherMedicalHistory = new javax.swing.JCheckBox();
        lbl_message2 = new javax.swing.JLabel();
        txt_OtherMedicalHistory = new javax.swing.JTextField();
        txt_MedicalRecordNo = new javax.swing.JTextField();
        txt_HealthPlanNo = new javax.swing.JTextField();
        chkbox_NA = new javax.swing.JCheckBox();
        lbl_Save = new javax.swing.JButton();
        lbl_Warning = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_HealthRecord_Title.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lbl_HealthRecord_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_HealthRecord_Title.setText("HEALTH RECORDS INFORMATION");
        lbl_HealthRecord_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbl_HealthRecord_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 11, -1, -1));

        lbl_MedicalRecordNo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_MedicalRecordNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_MedicalRecordNo.setText("* Medical Record Number : ");
        lbl_MedicalRecordNo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbl_MedicalRecordNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 59, -1, -1));

        lbl_HealthPlanNo.setText("* Health Plan Beneficiary Number :");
        add(lbl_HealthPlanNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 91, -1, -1));

        lbl_PreviousMedicalHist.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        lbl_PreviousMedicalHist.setText("Please select previous medical history if any");
        add(lbl_PreviousMedicalHist, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 133, 226, -1));
        add(lbl_message1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 175, -1, -1));

        chkbox_diabetes.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        chkbox_diabetes.setText("Diabetes");
        add(chkbox_diabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 150, -1, -1));

        chkbox_Hypertension.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        chkbox_Hypertension.setText("HyperTension");
        add(chkbox_Hypertension, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 150, -1, -1));

        chkbox_Allergies.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        chkbox_Allergies.setText("Allergies");
        add(chkbox_Allergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 150, -1, -1));

        chkbox_OtherMedicalHistory.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        chkbox_OtherMedicalHistory.setText("Others");
        add(chkbox_OtherMedicalHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 150, -1, -1));

        lbl_message2.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        lbl_message2.setText("In case of other medical history, kindly mention below");
        add(lbl_message2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 205, -1, -1));

        txt_OtherMedicalHistory.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        add(txt_OtherMedicalHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 226, 281, -1));

        txt_MedicalRecordNo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txt_MedicalRecordNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(txt_MedicalRecordNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 56, 130, -1));

        txt_HealthPlanNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_HealthPlanNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HealthPlanNoActionPerformed(evt);
            }
        });
        add(txt_HealthPlanNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 88, 133, -1));

        chkbox_NA.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        chkbox_NA.setText("Not Applicable");
        add(chkbox_NA, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 175, -1, -1));

        lbl_Save.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        lbl_Save.setText("Save");
        lbl_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_SaveActionPerformed(evt);
            }
        });
        add(lbl_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 265, -1, -1));

        lbl_Warning.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        lbl_Warning.setForeground(new java.awt.Color(255, 0, 0));
        lbl_Warning.setText("All fields marked with * are Mandatory.");
        add(lbl_Warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Interface/Electronic-Health-Records-Software.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 800, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_HealthPlanNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HealthPlanNoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_HealthPlanNoActionPerformed

    private void lbl_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_SaveActionPerformed
        // TODO add your handling code here:
        
        if (chkbox_diabetes.isSelected() == true)
        {
            Other_Medical_History = "Diabetes";
        }
        if (chkbox_Hypertension.isSelected() == true)
        {
            Other_Medical_History = Other_Medical_History + ", Hyper Tension";
        }
        if (chkbox_Allergies.isSelected() == true)
        {
            Other_Medical_History = Other_Medical_History + ", Allergies";
        }
        if (chkbox_NA.isSelected() == true)
        {
            Other_Medical_History = "Not Applicable";
        }
        if (chkbox_OtherMedicalHistory.isSelected() == true)
        {
            Other_Medical_History =   txt_OtherMedicalHistory.getText();
        }
        
        if (txt_MedicalRecordNo.getText().isBlank() || txt_HealthPlanNo.getText().isBlank() ) 
            JOptionPane.showMessageDialog(this, "Mandatory fields cannot be blank.");
        else
        {product.setMedical_Record_Number(txt_MedicalRecordNo.getText());
            product.setHealth_Plan_Number(txt_HealthPlanNo.getText());
            product.setOther_Medical_History(Other_Medical_History);
            JOptionPane.showMessageDialog(this, "Health Records has been Saved.");}
    }//GEN-LAST:event_lbl_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkbox_Allergies;
    private javax.swing.JCheckBox chkbox_Hypertension;
    private javax.swing.JCheckBox chkbox_NA;
    private javax.swing.JCheckBox chkbox_OtherMedicalHistory;
    private javax.swing.JCheckBox chkbox_diabetes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_HealthPlanNo;
    private javax.swing.JLabel lbl_HealthRecord_Title;
    private javax.swing.JLabel lbl_MedicalRecordNo;
    private javax.swing.JLabel lbl_PreviousMedicalHist;
    private javax.swing.JButton lbl_Save;
    private javax.swing.JLabel lbl_Warning;
    private javax.swing.JLabel lbl_message1;
    private javax.swing.JLabel lbl_message2;
    private javax.swing.JTextField txt_HealthPlanNo;
    private javax.swing.JTextField txt_MedicalRecordNo;
    private javax.swing.JTextField txt_OtherMedicalHistory;
    // End of variables declaration//GEN-END:variables
}
