/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Interface;

import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author swapn
 */
public class Main_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main_JFrame
     */
    
    Product product;
    
    public Main_JFrame() {
        initComponents();
        product = new Product();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane1 = new javax.swing.JSplitPane();
        titlePanel = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();
        btn_Create = new javax.swing.JButton();
        btn_display = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        titlePanel.setMinimumSize(new java.awt.Dimension(534, 100));
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Title.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Title.setText("Profile Management System");
        lbl_Title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_Title.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        lbl_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlePanel.add(lbl_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        btn_Create.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_Create.setText("Create New Profile");
        btn_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreateActionPerformed(evt);
            }
        });
        titlePanel.add(btn_Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        btn_display.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_display.setText("Display Existing Profile");
        btn_display.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_displayActionPerformed(evt);
            }
        });
        titlePanel.add(btn_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Interface/95-959676_simple-and-minimalist-wallpapers-data-src-shades-of.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        titlePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, 1620, 1680));

        SplitPane1.setTopComponent(titlePanel);

        controlPanel.setBackground(new java.awt.Color(255, 255, 255));
        controlPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        controlPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        controlPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Interface/38bccf37953ac4d2c9d7eb45859450ca.gif"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        controlPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 590, 600));

        SplitPane1.setRightComponent(controlPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreateActionPerformed
        // TODO add your handling code here:
        
        CreateJPanel createjpanel = new CreateJPanel(product);
        SplitPane1.setBottomComponent(createjpanel);
        
        
    }//GEN-LAST:event_btn_CreateActionPerformed

    private void btn_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_displayActionPerformed
        // TODO add your handling code here:
        
            ViewJPanel viewjpanel = new ViewJPanel(product);
            SplitPane1.setBottomComponent(viewjpanel);
        
        
    }//GEN-LAST:event_btn_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane1;
    private javax.swing.JButton btn_Create;
    private javax.swing.JButton btn_display;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
