/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Interface;

import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author swapn
 */
public class ProfessionalNetworkInfoJPanel extends javax.swing.JPanel {
    
    Product product;

    /**
     * Creates new form SocialMediaInfoJPanel
     */
    public ProfessionalNetworkInfoJPanel(Product product) {
        initComponents();
        this.product = product ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ProfessionalNetwork_Title = new javax.swing.JLabel();
        lbl_LinkedinUrl = new javax.swing.JLabel();
        lbl_IPAddress = new javax.swing.JLabel();
        txt_LinkedinUrl = new javax.swing.JTextField();
        txt_IPAddress = new javax.swing.JTextField();
        lbl_Save = new javax.swing.JButton();
        lbl_Warning = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ProfessionalNetwork_Title.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        lbl_ProfessionalNetwork_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ProfessionalNetwork_Title.setText("PROFESSIONAL NETWORK INFORMATION");
        lbl_ProfessionalNetwork_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lbl_ProfessionalNetwork_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 11, -1, -1));

        lbl_LinkedinUrl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbl_LinkedinUrl.setText("* LinkedIn URL : ");
        add(lbl_LinkedinUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 55, -1, -1));

        lbl_IPAddress.setText("* Internet Protocol Address : ");
        add(lbl_IPAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 92, -1, -1));

        txt_LinkedinUrl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        add(txt_LinkedinUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 52, 150, -1));

        txt_IPAddress.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        add(txt_IPAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 91, 150, -1));

        lbl_Save.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        lbl_Save.setText("Save");
        lbl_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_SaveActionPerformed(evt);
            }
        });
        add(lbl_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 130, -1, -1));

        lbl_Warning.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        lbl_Warning.setForeground(new java.awt.Color(255, 0, 0));
        lbl_Warning.setText("All fields marked with * are Mandatory.");
        add(lbl_Warning, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Interface/online profile gif.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_SaveActionPerformed
        // TODO add your handling code here:
        
        if (txt_LinkedinUrl.getText().isBlank() || txt_IPAddress.getText().isBlank())
            JOptionPane.showMessageDialog(this, "Mandatory fields cannot be blank.");
        else
        {product.setLinkedIn_URL(txt_LinkedinUrl.getText());
            product.setIP_Address(txt_IPAddress.getText());
            JOptionPane.showMessageDialog(this, "Professional Network details has been saved.");}
    }//GEN-LAST:event_lbl_SaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_IPAddress;
    private javax.swing.JLabel lbl_LinkedinUrl;
    private javax.swing.JLabel lbl_ProfessionalNetwork_Title;
    private javax.swing.JButton lbl_Save;
    private javax.swing.JLabel lbl_Warning;
    private javax.swing.JTextField txt_IPAddress;
    private javax.swing.JTextField txt_LinkedinUrl;
    // End of variables declaration//GEN-END:variables
}
